# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c0dccc45a1cce0f9a48e48d4af90f9735e98a371ed9b90e72996f23c3733043fe42ccd1c806f52862414a8e8aaf813369346fd8d362f36a1e0ea05d1bb10cdf

test:
  secret_key_base: 91743dfc54794c1566e07d8cbeb4b367025f37fcc5ca26509770b5e65a3416fd0318d626a2aef2e82f49b883efd3720687c14c2fab6cb48201b27a86e9851ffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
